AWS_ACCESS_KEY_ID = "AKIA5XQWKVMX6XOCJYWP"
AWS_SECRET_ACCESS_KEY = "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"
AWS_DEFAULT_REGION = "us-east-1"

SNOWFLAKE_USER = "JITSAHA458"
SNOWFLAKE_PASSWORD = "RTG#22082001rtg"
SNOWFLAKE_ACCOUNT = "xuruali-xb11321"
SNOWFLAKE_WAREHOUSE = "TEST_RAW_WH"
SNOWFLAKE_DATABASE = "TEST_RAW"
SNOWFLAKE_SCHEMA = "PUBLIC"
